ros-controls/control_toolbox

include/control_toolbox/pid.h, src/pid.cpp, test/pid_tests.cpp
The integral of the error is computed in a class member, and the integral contribution is computed as of it, instead of doing all together. Now, setting the integral gain to zero dynamically cancel the integral contribution.
Additional update:
Function `getCurrentPIDErrors(...)` now returns the integral of the position error, and not the contribution. Because of this, also the tests were modified. Tests `integrationWindupZeroGainTest` (actually, this one makes no sense now, since the error is directly given instead of obtaining by diving the term by the gain) and `integrationWindupTest` check the windup constraint on the computed command.
I don't know how this affects the dependant packages, but I believe the change is worthy.
Resolve #32.
=> Improvement on the integral contribution implementation

src/pid.cpp
computeCommand is documented to use 'error = target - state' rather than the old 'pError = pState-pTarget' of updatePid. One of the computeCommand implementations behaves correctly (https://github.com/ros-controls/control_toolbox/blob/indigo-devel/src/pid.cpp#L372), but this one does not (https://github.com/ros-controls/control_toolbox/blob/indigo-devel/src/pid.cpp#L372).
Next pull will be to chain the calls and prevent this kind of divergence.
=> Update computeCommand call to match documented/expected behaviour

cfg/Parameters.cfg
dynamic reconfigure only allows setting positive values for PID gains although negative values can be set using setGain.
=> changed the range of dynamic reconfigure to allow negative ones

test/pid_tests.cpp
Could be that #40 happened mainly due to 2 things (well, 3, if you count my awkwardness):
1. Lack of tests on command computation, as already requested by @adolfo-rt in #41
2. The `computeCommand` method has two signatures with almost a replica of code within -> Same code in two places requires update in two places -> The chance of making a mistake when updating increases.
In this initial PR both are addressed, there are 2 separated commits to easy the review.
First, in 9dc84fd548c0bd7df9d428cf60594fde24ea2b6d, the coverage of the PID class test suite is increased with the following modification of current tests:
* `zeroITermBadIBoundsTest`: I think that entering `i_max < i_min` should be prevented, or at least warned. A suggested change to avoid bad i-bounds is there commented because it …
=> Response to #40

include/control_toolbox/pid.h, src/pid.cpp
Otherwise the Pid class depends on the existance of a ROS node even when the math part is initialized only. (Pid() constructor and no init called)
This makes tests fail and could potentially lead to weird behaviours when used elsewhere.
Currenly the prerelease fails like this:
```
/tmp/catkin_workspace/devel_isolated/control_toolbox/lib/control_toolbox/pid_tests --gtest_output=xml:/tmp/catkin_workspace/test_results/control_toolbox/gtest-pid_tests.xml
[==========] Running 10 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 6 tests from ParameterTest
[ RUN      ] ParameterTest.ITermBadIBoundsTest
[FATAL] [1462284621.736137091]: You must call ros::init() before creating the first NodeHandle
Couldn't find an AF_INET address for []
Couldn't find an AF_INET …
```
=> RealtimePublisher only initialized if used.

CMakeLists.txt, include/control_toolbox/pid.h, src/pid.cpp
I noticed some API changes have been introduced in #52 when compiling our code for kinetic.
This will rollback the API changes without changing functionality.
See discussion in #34 
@paulbovbel @bmagyar
=> rollback API changes in PID class

CMakeLists.txt
Needed because of the usage here:
https://github.com/ros-controls/control_toolbox/blob/ba1100638a48a461e4e642150f4ae666303e3ecc/include/control_toolbox/pid.h#L40
=> Add control_msgs to CATKIN_DEPENDS.

src/pid.cpp, test/pid_tests.cpp
If gains.i_gain_ < 0 and std::abs(gains.i_min_) != std::abs(gains.i_max_), there would be a bug.  
For example: i_error_ = 0.1, gains.i_gain_ = -2.5, gains.i_min_ = -0.2, gains.i_max_ = 0.5.  
Then the calculated i_term would be -0.25, which is out of the range [-0.2, 0.5]
=> fixed an antiwindup bug

include/control_toolbox/sinusoid.h
`sinusoid.h` includes `<iostream>`, but it is only used in `sinusoid.cpp`. 
https://github.com/ros-controls/control_toolbox/blob/87c3ca1efedaa5740b517ac706c27d56ee6b3559/src/sinusoid.cpp#L39
This PR removes the extra include from the header since it's unused there.
=> Remove Extra include of iostream

CMakeLists.txt
This bumps the minimum CMake version to 3.0.2, which is the [minimum supported by ROS Kinetic](https://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021) and new enough to default to the NEW behavior of [CMP0048](https://cmake.org/cmake/help/v3.0/policy/CMP0048.html). This avoids a CMake warning when building and testing this package in Debian Buster and Ubuntu Focal.
=> [noetic] Bump CMake version to avoid CMP0048 warning

CMakeLists.txt
Is there any reason why control_toolbox is not a shared library ?
=> Created a shared library

include/control_toolbox/pid.hpp, src/pid.cpp, test/pid_publisher_tests.cpp
Similar idea to the parameter prefix PR https://github.com/ros-controls/control_toolbox/pull/94. In this case the topic name will be the same for all the pids. Adding this argument we can split them in different topics.
=> Added topic_prefix to publisher topic name

src/pid.cpp
Avoid crash in pid class when the type of the parameter doesn't match
=> Avoid crash in pid class when the type of the parameter doesn't match

include/control_toolbox/pid.h, src/pid.cpp, test/pid_tests.cpp
1. Currently after a reset (or init), since p_error_last is_ set to 0, the first computeCommand is calculating
a false large derivative error. Proposed fix: only calculate error_dot if p_error_last_ contains a real value.
2. Allow setting initial i_error. This allows PID to be used in a smoother manner in systems switching from
manual to automatic modes. [Reference](http://brettbeauregard.com/blog/2011/04/improving-the-beginner%E2%80%99s-pid-initialization/)
3. Improve cases where dt==0 or invalid errors were given (return last cmd_ instead of 0)
=> Allow smoother resets

cfg/Parameters.cfg
In a recent application we have found that we needed an a integral gain of around 7500 - 10000, which is rather larger than the +-1000 limits enforced by the dynamic reconfigure parameters in `Parameters.cfg`. Whether having an integral gain this high is actually a good idea or not is another matter... but it would be nice to be able to try it out without being constrained by artificial limits :smiley:
This change simply increases the limits of the integral gain from +-1000 to +-100000 which provides ample wiggle room, at the expense of the sliders being harder to fine tune in dynamic reconfigure. Seeing as the P gain limits are already +-100000, I figured this wouldn't be too much of an issue.
=> Increased integral gains & windup limits from +-1000 to +-100000

include/control_toolbox/pid_ros.hpp, src/pid_ros.cpp
- Fix the issue when setting the parameters of `PidROS` with topic prefix
```shell
$ ros2 param set /gimbal_controller pitch.p 1.5
Setting parameter failed: Invalid parameter
```
- Add getParametersCallbackHandle function so that user can remove set_parameters_callback to avoid issue like https://github.com/ros-controls/control_toolbox/issues/118
```cpp
node_->remove_on_set_parameters_callback(pid_ros_->getParametersCallbackHandle().get());
```
=> [PidROS] Add topic_prefix_ to declareParam & setParameter

include/control_toolbox/pid_ros.hpp, src/pid_ros.cpp
I'm trying to used IMU data to do the PID control. And I'm using calculated angle from IMU to compute the `error` and using angular velocity directly read from IMU to compute the `error_dot`. So passing in derivative error is needed.
=> [PidROS] Support pass in a precomputed derivative error

include/control_toolbox/pid_ros.hpp, src/pid_ros.cpp, test/pid_parameters_tests.cpp
This fixes problems in PidROS with using the parameters (reconfiguration fails when the node has extra parameters declared) and with namespacing issues (topic namespace argument can lead to problems if defined deeper than one)
=> Fix namespace collision and parameter_callback problems in PidROS

CMakeLists.txt
The library has four dependencies but only three are exported. This produces that packages using anything from `control_toolbox` which uses `control_msgs` is going to fail (`pid_ros.hpp`)
Adding the missing dependency to the ones exported.
=> Export missing dependency

include/control_toolbox/pid.hpp
The documentation in the header (published via [doxygen](http://docs.ros.org/en/api/control_toolbox/html/classcontrol__toolbox_1_1Pid.html)) was different than implemented (and different to control theory standards).
For ros2: Is the public page of these api docs currently maintained? The link above has broken images, as mentioned in #64
=> Correct documentation (signs in PID control law)

CMakeLists.txt, package.xml
=> Fix overriding of package

.github/workflows/ci-format.yml, .pre-commit-config.yaml
- Use pydocstyle instead of pep257 because it replaces it.
- Bump versions of hooks.
- Remove fixed python version from formatting action.
- Fix action warnings about Node.js 12 by updating them.
- Bump version of clang-format.
#131 corrects formatting - not sure why clang-format is passing here and not locally...
=> 🔧Fixes and updated on pre-commit hooks and their action.

include/control_toolbox/pid.hpp
In some cases, internal values of PID have to be manipulated to work on hardware. This change enables to subclass the PID implementation and adjust internal states as needed.
=> Enable subclassing of PID implementation.

.github/workflows/humble-debian-build.yml, .github/workflows/humble-rhel-binary-build.yml, .github/workflows/iron-debian-build.yml, .github/workflows/iron-rhel-binary-build.yml, .github/workflows/rolling-debian-build.yml, .github/workflows/rolling-rhel-binary-build.yml
Add RHEL and debian CI jobs.
I can't reproduce the error of the `RHEL humble` test locally in the container, but here it consistently fails.
=> [CI] Add RHEL and debian jobs

.github/workflows/build-source_rollling.yml, .github/workflows/humble-rhel-binary-build.yml, .github/workflows/iron-rhel-binary-build.yml, .github/workflows/rolling-rhel-binary-build.yml
There was the wrong branch in the rolling source build workflow, see [here](https://github.com/ros-controls/control_toolbox/actions/workflows/build-source_rollling.yml).
I also add `--rosdistro $ROS_DISTRO` to rosdep for the binary workflows
=> [CI] Fix source build

CMakeLists.txt, package.xml
I changed the CMake file to use Eigen's CMake target as described here https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html
This fixes #178 for RHEL 8
=> Use Eigen CMake target

.github/workflows/rosdoc2.yml, .pre-commit-config.yaml, README.md, doc/conf.py, doc/index.rst, package.xml
rosdoc2 will be used by the build farm to publish API docs on http://docs.ros.org/en/rolling/p/control_toolbox/
- Add custom landing page for rosdoc2: logo, links to control.ros.org
- Copy over information from https://wiki.ros.org/control_toolbox
- add rosdoc2 workflow, but only if the relevant files changed
=> Add custom rosdoc2 config

include/control_toolbox/pid.hpp, test/pid_tests.cpp
- improve function docs
- add [[nodiscard]] to computeCommand
=> PID: Improve the API docs and change default value of antiwindup

LICENSE, LICENSE.BSD-3-clause, README.md, package.xml
We already have a mix of BSD-3-Clause and Apache-2 licenses in the file. I suggest changing the main LICENSE to Apache, but keep the old one, too.
There are several references online doing so, and github theoretically supports several licenses per repo: https://github.blog/open-source/open-source-license-usage-on-github-com/
btw: I also updated the maintainers in the package.xml
=> Change license to Apache-2

include/control_toolbox/pid.hpp
The includes are necessary for PidROS living in its own file.
=> PID class does not depend on rclcpp

.github/workflows/build-semi-binary.yml
Now we have the situation that binary testing builds fail, but don't see if this repo with realtime_tools compiled from source would work.
=> Add semi-binary build

.github/workflows/abi-compatibility.yml, .github/workflows/build-binary.yml, .github/workflows/build-semi-binary.yml, .github/workflows/build-source.yml, .github/workflows/ci-pre-commit.yml, .github/workflows/debian-build.yml, .github/workflows/rhel-semi-binary-build.yml, README.md, control_toolbox-not-released.iron.repos, control_toolbox.iron.repos
Due after the next patch release on November 15th.
=> Remove iron workflows and update readme

include/control_toolbox/rate_limiter.hpp, test/rate_limiter.cpp
> [!NOTE]  
> This is a duplicate of a now closed PR against `ros-controls/ros2_controllers` (see [PR #1390](https://github.com/ros-controls/ros2_controllers/pull/1390)) that was initially intended for the `diff_drive_controller`.
> I was asked to move it here since the rate_limiter of the `diff_drive_controller` will be that of the `control_toolbox` (see [ros2_controllers,  PR #1315](https://github.com/ros-controls/ros2_controllers/pull/1315)).
Hi,
There seem to be an error in the jerk limiter ([speed_limiter.hpp #L290-L311](https://github.com/ros-controls/control_toolbox/blob/641c92954dbae1af0435cdeb105cbf5a1578d152/include/control_toolbox/rate_limiter.hpp#L290-L311)) caused by the (as far as I can tell) incorrect factor 2 in the computation of the velocity limit resulting from jerk …
=> Fix jerk limiter in rate_limiter

CMakeLists.txt, include/control_filters/custom_validators.hpp, include/control_filters/rate_limiter.hpp, include/control_toolbox/rate_limiter.hpp, src/control_filters/rate_limiter_parameters.yaml, test/control_filters/test_load_rate_limiter.cpp, test/control_filters/test_rate_limiter.cpp, test/control_filters/test_rate_limiter.hpp, test/control_filters/test_rate_limiter_parameters.yaml
I ran in the same issue as was solved with diff_drive_controller already https://github.com/ros-controls/ros2_controllers/pull/252
I added some tests, and furthermore improved the generate_parameter_library parameter declaration file.
=> Fix bug in rate_limiter filter and add more tests

.github/workflows/build-binary.yml, include/control_toolbox/low_pass_filter.hpp, src/pid_ros.cpp, test/pid_tests.cpp
See https://github.com/ros-controls/realtime_tools/pull/207
clang was complaining about implicit conversions in the PID class.
=> Add job for clang build

CMakeLists.txt, control_filters.xml, include/control_filters/exponential_filter.hpp, src/control_filters/README.md, src/control_filters/exponential_filter.cpp, src/control_filters/exponential_filter_parameters.yaml, test/control_filters/test_exponential_filter.cpp, test/control_filters/test_exponential_filter.hpp, test/control_filters/test_exponential_filter_parameters.yaml, test/control_filters/test_load_exponential_filter.cpp
Similar to `control_filters/LowPassFilter`, the filter itself was already there.
=> Add filter plugin for exponential filter

CMakeLists.txt
Someone forgot to check if the tests run at all :angel:
=> Add missing exponential_filter export and tests

include/control_filters/exponential_filter.hpp, include/control_filters/low_pass_filter.hpp, include/control_filters/rate_limiter.hpp, test/control_filters/test_exponential_filter.cpp, test/control_filters/test_exponential_filter_parameters.yaml
Address https://github.com/ros-controls/control_toolbox/issues/257
@christophfroehlich , regarding to catch(...), I left it out since I am not sure what would be useful to log. I'm open to add it if you could provide some suggestions.
=> Update plugin lib exception handling

.github/workflows/abi-compatibility.yml, include/control_filters/exponential_filter.hpp, include/control_filters/low_pass_filter.hpp, include/control_filters/rate_limiter.hpp
Needs [release 0.4.0](https://github.com/PickNikRobotics/generate_parameter_library/pull/232)
for reference, see https://github.com/PickNikRobotics/generate_parameter_library/pull/213
=> Update include paths of GPL

control_toolbox.humble.repos, control_toolbox.jazzy.repos, ros_controls.jazzy.repos, ros_controls.rolling.repos
- Upstream, we branched already for jazzy
- Downstream, we don't need to repeat the repos from the control_toolbox repos file since #301
=> Update upstream/downstream repository branches

CMakeLists.txt, package.xml, test/control_filters/test_exponential_filter.cpp, test/control_filters/test_load_exponential_filter.cpp, test/control_filters/test_load_low_pass_filter.cpp, test/control_filters/test_load_rate_limiter.cpp, test/control_filters/test_low_pass_filter.cpp, test/control_filters/test_rate_limiter.cpp, test/pid_ros_parameters_tests.cpp, test/pid_ros_publisher_tests.cpp, test/pid_tests.cpp
This PR resolves [this issue](https://github.com/ros-controls/control_toolbox/issues/256).
=> Replaced gMock instead of gTest

control_toolbox/src/pid.cpp, control_toolbox/test/pid_tests.cpp
Fixes #31 
- return the same command if update is called with dt=0
- return NaN if called with any error being NaN, but not change internal states for fast recovery afterwards.
=> Don't return cmd if called with dt=0 or garbage

control_toolbox/include/control_filters/exponential_filter.hpp, control_toolbox/include/control_filters/rate_limiter.hpp
While reviewing #162 I realized that we have somewhere `clock_` member variables, but never use them.
=> Remove unused class variables

control_toolbox/control_filters.xml, control_toolbox/include/control_filters/low_pass_filter.hpp, control_toolbox/include/control_toolbox/low_pass_filter.hpp, control_toolbox/src/control_filters/low_pass_filter.cpp, control_toolbox/test/control_filters/test_load_low_pass_filter.cpp, control_toolbox/test/control_filters/test_low_pass_filter.cpp
This PR adds the option to create a `LowPassFilter` object with type `std::vector<double>` (seeing that most system interfaces are this type :smile: )
The velocity data from my robot is noisy so I needed to clean it up
to
=> Add std::vector<double> option to the low pass filter

control_toolbox/src/pid_ros.cpp
PID is broken now since https://github.com/ros-controls/control_msgs/pull/178#issuecomment-2827623456
=> Cleanup removed msg fields

.github/workflows/rolling-compatibility-build.yml
Rolling testing fails because realtime_tools is broken buildfarm
=> Add compatibility build workflow

control_toolbox/CMakeLists.txt
As of the ROS 2 Kilted release [`ament_target_dependencies` is deprecated.](https://docs.ros.org/en/kilted/Releases/Release-Kilted-Kaiju.html#ament-target-dependencies-is-deprecated)
This PR updates the syntax. Caution should be used to ensure that the target branch is not used for other ROS 2 distros.
Note: This PR was generated by a bot script, but using the simple pattern matching of the [`ros_glint`](https://github.com/MetroRobots/ros_glint) library. No LLMs were used.
=> [kilted] Update deprecated call to ament_target_dependencies

.pre-commit-config.yaml, doc/control_filters.md, doc/control_toolbox.md, doc/index.rst, doc/migration.rst, doc/release_notes.rst
No new information, just moving it to a location to include in control.ros.org
---
=> Add docs for control.ros.org

control_toolbox/CMakeLists.txt, control_toolbox/include/control_toolbox/filter_traits.hpp, control_toolbox/package.xml
https://github.com/ros-controls/ros2_controllers/pull/560 fails because filter_chains does not initialize intermediate output variables, which makes the assertion `data_in.header.frame_id == data_out.header.frame_id` fail.
I also changed the assertions to throwing exceptions, using fmt to concatenate numbers and strings.
=> Don't validate data_out if it is empty

control_toolbox/include/control_toolbox/pid.hpp, control_toolbox/include/control_toolbox/pid_ros.hpp, control_toolbox/src/pid.cpp, control_toolbox/src/pid_ros.cpp, control_toolbox/test/pid_ros_parameters_tests.cpp, control_toolbox/test/pid_ros_publisher_tests.cpp, control_toolbox/test/pid_tests.cpp
This PR consists of changes to cleanup the saturation boolean of the PID toolbox
=> Cleanup saturation parameter in the methods and constructors

control_toolbox/src/pid_ros.cpp
I'm not sure why the callback is executed before the parameter is declared. How should we fix this? just skip it, or auto-declare?
Fixes https://github.com/ros-controls/ros2_control_ci/issues/364
Fixes https://github.com/ros-controls/ros2_control_ci/issues/365
Fixes https://github.com/ros-controls/ros2_control_ci/issues/366
Fixes https://github.com/ros-controls/ros2_control_ci/issues/367
Fixes https://github.com/ros-controls/ros2_control_ci/issues/368
Fixes https://github.com/ros-controls/ros2_control_ci/issues/369
Fixes https://github.com/ros-controls/ros2_control_ci/issues/370
Fixes https://github.com/ros-controls/ros2_controllers/issues/1754
=> Skip callback if saturation parameter is not declared

control_toolbox/CMakeLists.txt, control_toolbox/include/control_toolbox/pid.hpp, control_toolbox/include/control_toolbox/pid_ros.hpp, control_toolbox/src/pid.cpp, control_toolbox/src/pid_ros.cpp, control_toolbox/test/pid_ros_parameters_tests.cpp, control_toolbox/test/pid_ros_publisher_tests.cpp, control_toolbox/test/pid_tests.cpp
Second PR for the antiwindup strategy integration
=> Redefine the antiwindup strategy and their parameters interfacing

.github/workflows/jazzy-check-docs.yml, .github/workflows/rolling-check-docs.yml, doc/migration.rst, doc/release_notes.rst
https://github.com/ros-controls/control.ros.org/pull/470
=> Add CI job for docs

control_toolbox/include/control_toolbox/pid_ros.hpp, control_toolbox/src/pid_ros.cpp, control_toolbox/test/pid_ros_parameters_tests.cpp, control_toolbox/test/pid_ros_publisher_tests.cpp, doc/migration.rst, doc/release_notes.rst
See https://github.com/ros-controls/control_toolbox/issues/156#issuecomment-2985605034
Fixes #156
=> Deprecate `prefix_is_for_params` of PidROS

control_toolbox/CMakeLists.txt, control_toolbox/package.xml
The fmt public dependency was added in the C++ code in https://github.com/ros-controls/control_toolbox/pull/410, but without properly declaring the dependency in CMake and package.xml . The issue in the `ros2-master` branch was fixed by https://github.com/ros-controls/control_toolbox/pull/391, but that PR was not backported to the `jazzy` branch.
To send us a pull request, please:
=> [jazzy] Add missing public dependency on fmt library

control_toolbox/src/pid_ros.cpp, control_toolbox/test/pid_ros_parameters_tests.cpp
Resolves #442 
I fixed the tests, we haven't tested all the parameters with `initialize_from_ros_parameters`
=> Declare missing parameters for PID

control_toolbox/include/control_filters/gravity_compensation.hpp
Fixes
```
In file included from /workspaces/ros2_rolling_ws/src/control_toolbox/control_toolbox/include/control_filters/gravity_compensation.hpp:25,
from /workspaces/ros2_rolling_ws/src/control_toolbox/control_toolbox/test/control_filters/test_load_gravity_compensation.cpp:19:
/opt/ros/rolling/include/tf2_ros/tf2_ros/buffer.h:40:4: warning: #warning BUFFER_HEADER_DEPRECATION [-Wcpp]
40 |   #warning BUFFER_HEADER_DEPRECATION
|    ^~~~~~~
In file included from /workspaces/ros2_rolling_ws/src/control_toolbox/control_toolbox/include/control_filters/gravity_compensation.hpp:26:
/opt/ros/rolling/include/tf2_ros/tf2_ros/transform_listener.h:40:4: warning: #warning TRANSFORM_LISTENER_HEADER_DEPRECATION [-Wcpp]
40 |   #warning TRANSFORM_LISTENER_HEADER_DEPRECATION
|    ^~~~~~~
---
```
=> Fix deprecated TF headers

control_toolbox/CHANGELOG.rst
Catkin scripts complain
```
<string>:344: (ERROR/3) Unknown target name: "i_min".
<string>:344: (ERROR/3) Unknown target name: "i_max".
<string>:345: (ERROR/3) Unknown target name: "i_gain".
<string>:363: (ERROR/3) Unknown target name: "i_gain".
<string>:363: (ERROR/3) Unknown target name: "i_gain".
<string>:363: (ERROR/3) Unknown target name: "i_error".
<string>:363: (ERROR/3) Unknown target name: "i_term".
<string>:363: (ERROR/3) Unknown target name: "i_error".
<string>:363: (ERROR/3) Unknown target name: "i_term".
<string>:363: (ERROR/3) Unknown target name: "i_error".
<string>:363: (ERROR/3) Unknown target name: "i_error".
<string>:344: (ERROR/3) Unknown target name: "i_min".
<string>:344: (ERROR/3) Unknown target name: "i_max".
<string>:345: (ERROR/3) Unknown target name: "i_gain". …
```
=> Fix rst errors

control_toolbox/test/control_filters/test_exponential_filter.cpp, control_toolbox/test/control_filters/test_low_pass_filter.cpp, control_toolbox/test/control_filters/test_rate_limiter.cpp
```
/workspaces/ros2_rolling_ws/src/control_toolbox/control_toolbox/test/control_filters/test_rate_limiter.cpp:76:32: warning: variable 'in' is uninitialized when passed as a const reference argument here [-Wuninitialized-const-reference]
76 |   ASSERT_THROW(filter_->update(in, out), std::runtime_error);
|                                ^~
```
https://github.com/ros-controls/ros2_control_cmake/pull/15
=> Fix -Wuninitialized-const-reference

.github/workflows/humble-abi-compatibility.yml, .github/workflows/humble-binary-build.yml, .github/workflows/humble-build-coverage.yml, .github/workflows/humble-build-downstream.yml, .github/workflows/humble-build-source.yml, .github/workflows/humble-debian-build.yml, .github/workflows/humble-rhel-semi-binary-build.yml, .github/workflows/humble-semi-binary-build.yml, .github/workflows/jazzy-abi-compatibility.yml, .github/workflows/jazzy-binary-build.yml, .github/workflows/jazzy-build-coverage.yml, .github/workflows/jazzy-build-downstream.yml, .github/workflows/jazzy-build-source.yml, .github/workflows/jazzy-debian-build.yml, .github/workflows/jazzy-rhel-semi-binary-build.yml, .github/workflows/jazzy-semi-binary-build.yml, .github/workflows/rolling-abi-compatibility.yml, .github/workflows/rolling-binary-build.yml, .github/workflows/rolling-build-coverage.yml, .github/workflows/rolling-build-downstream.yml, .github/workflows/rolling-build-source.yml, .github/workflows/rolling-compatibility-build.yml, .github/workflows/rolling-debian-build.yml, .github/workflows/rolling-rhel-semi-binary-build.yml, .github/workflows/rolling-semi-binary-build-win.yml, .github/workflows/rolling-semi-binary-build.yml
as we have in ros2_control repo
=> [CI] Add paths filters
