- include/control_toolbox/pid.h
- src/pid.cpp
Remove code repetition by collapsing deprecated computeCommand into negative updatePid function call
> Remove code repetition

- CMakeLists.txt
- include/control_toolbox/pid.h
- msg/PidState.msg
- package.xml
- src/pid.cpp
> Add optional state publishing to PID controller

- cfg/Parameters.cfg
- include/control_toolbox/pid.h
- src/pid.cpp
- src/pid_gains_setter.cpp
- srv/SetPidGains.srv
- test/pid_tests.cpp
> Add antiwindup to PID controller 

- cfg/Parameters.cfg
More concise version of [PR 57](https://github.com/ros-controls/control_toolbox/pull/57).
> Squashed #57

- .travis.yml
supersedes #63 
closes #61 
same as https://github.com/ros-controls/realtime_tools/pull/20
> switched to industrial_ci

- .travis.yml
See also ros-controls/ros_control#440
> Migrate to new industrial_ci

- scripts/tune_pid.py
Sorry, I missed that one in https://github.com/ros-controls/control_toolbox/pull/90
> Python 3 compat part II

- .github/workflows/lint.yml
> Remove copyright linting

- CMakeLists.txt
- include/control_toolbox/pid.hpp
- package.xml
Related to this comment https://github.com/ros-controls/control_toolbox/pull/97#issuecomment-651588944
> [ROS 2] Package Improvements

- .github/workflows/test.yml
- include/control_toolbox/dither.hpp
> remove unused variables

- .github/workflows/format.yml
- .pre-commit-config.yaml
bringing it up to date with the [ros2_control repo](https://github.com/ros-controls/ros2_control/blob/master/.pre-commit-config.yaml)
> Update pre commit

- include/control_toolbox/pid.hpp
```cpp
rclcpp::Time last_time = get_clock()->now();
while (true) {
rclcpp::Time time = get_clock()->now();
double effort = pid.computeCommand(position_desi_ - currentPosition(), (time - last_time).nanoseconds());
last_time = time;
}
```
> Update documentation to reflect ROS 2 usage

- include/control_toolbox/pid.hpp
- include/control_toolbox/pid_ros.hpp
Needs https://github.com/ros-controls/realtime_tools/pull/206 and https://github.com/ros-controls/realtime_tools/pull/225
> Change the realtime_tools header extensions

- test/pid_parameters_tests.cpp
- test/pid_publisher_tests.cpp
Similar to https://github.com/ros-controls/ros2_controllers/pull/1470
> Fix lifecycle warning in test

- ros_controls.jazzy.repos
https://github.com/ros-controls/realtime_tools/pull/263
> Use jazzy branch for realtime_tools

- .github/workflows/humble-abi-compatibility.yml
- .github/workflows/rolling-abi-compatibility.yml
Needs https://github.com/ros-controls/ros2_control_ci/pull/236
> Use ABI workflow from ros2_control_ci

- src/pid_ros.cpp
follow-up to #294, needs 
https://github.com/ros-controls/control_msgs/pull/179
> [PidRos] Cleanup duplicate entries in the msg definition

- srv/SetPidGains.srv
we don't use it (never did in ROS 2?)
> Remove unused srv file

- LICENSE.BSD-3-clause
See https://opensource.org/license/bsd-3-clause and https://github.com/ros-controls/control_msgs/issues/120
> Add copyright owner

- .clang-format
- control_toolbox/include/control_filters/custom_validators.hpp
- control_toolbox/include/control_filters/exponential_filter.hpp
- control_toolbox/include/control_filters/gravity_compensation.hpp
- control_toolbox/include/control_filters/low_pass_filter.hpp
- control_toolbox/include/control_filters/rate_limiter.hpp
- control_toolbox/include/control_toolbox/dither.hpp
- control_toolbox/include/control_toolbox/low_pass_filter.hpp
- control_toolbox/include/control_toolbox/pid.hpp
- control_toolbox/include/control_toolbox/pid_ros.hpp
- control_toolbox/include/control_toolbox/rate_limiter.hpp
- control_toolbox/src/control_filters/gravity_compensation.cpp
- control_toolbox/src/dither.cpp
- control_toolbox/src/limited_proxy.cpp
- control_toolbox/src/pid.cpp
- control_toolbox/src/pid_ros.cpp
- control_toolbox/src/sine_sweep.cpp
- control_toolbox/test/control_filters/test_exponential_filter.cpp
- control_toolbox/test/control_filters/test_filter_util.hpp
- control_toolbox/test/control_filters/test_gravity_compensation.cpp
- control_toolbox/test/control_filters/test_load_exponential_filter.cpp
- control_toolbox/test/control_filters/test_load_gravity_compensation.cpp
- control_toolbox/test/control_filters/test_load_low_pass_filter.cpp
- control_toolbox/test/control_filters/test_load_rate_limiter.cpp
- control_toolbox/test/control_filters/test_low_pass_filter.cpp
- control_toolbox/test/control_filters/test_rate_limiter.cpp
- control_toolbox/test/pid_ros_parameters_tests.cpp
- control_toolbox/test/pid_ros_publisher_tests.cpp
- control_toolbox/test/pid_tests.cpp
- control_toolbox/test/rate_limiter.cpp
pre-commit didn't report such errors in my local devcontainer, so I wondered why: This repository is missing a .clang-format file, and the fallback-style for clang-format is set to 'None' -> no format at all.
> Fix clang-format

- .clang-format
- control_toolbox/include/control_filters/custom_validators.hpp
- control_toolbox/include/control_filters/exponential_filter.hpp
- control_toolbox/include/control_filters/gravity_compensation.hpp
- control_toolbox/include/control_filters/low_pass_filter.hpp
- control_toolbox/include/control_filters/rate_limiter.hpp
- control_toolbox/include/control_toolbox/dither.hpp
- control_toolbox/include/control_toolbox/low_pass_filter.hpp
- control_toolbox/include/control_toolbox/pid.hpp
- control_toolbox/include/control_toolbox/pid_ros.hpp
- control_toolbox/include/control_toolbox/rate_limiter.hpp
- control_toolbox/src/control_filters/gravity_compensation.cpp
- control_toolbox/src/dither.cpp
- control_toolbox/src/limited_proxy.cpp
- control_toolbox/src/pid.cpp
- control_toolbox/src/pid_ros.cpp
- control_toolbox/src/sine_sweep.cpp
- control_toolbox/test/control_filters/test_exponential_filter.cpp
- control_toolbox/test/control_filters/test_filter_util.hpp
- control_toolbox/test/control_filters/test_gravity_compensation.cpp
- control_toolbox/test/control_filters/test_load_exponential_filter.cpp
- control_toolbox/test/control_filters/test_load_gravity_compensation.cpp
- control_toolbox/test/control_filters/test_load_low_pass_filter.cpp
- control_toolbox/test/control_filters/test_load_rate_limiter.cpp
- control_toolbox/test/control_filters/test_low_pass_filter.cpp
- control_toolbox/test/control_filters/test_rate_limiter.cpp
- control_toolbox/test/pid_ros_parameters_tests.cpp
- control_toolbox/test/pid_ros_publisher_tests.cpp
- control_toolbox/test/pid_tests.cpp
- control_toolbox/test/rate_limiter.cpp
> Fix clang-format (backport #327)

- .clang-format
- control_toolbox/include/control_toolbox/low_pass_filter.hpp
- control_toolbox/src/pid.cpp
A follow-up of https://github.com/ros-controls/control_toolbox/pull/344
> Minor filter fixes + clang-format rules update

- .github/workflows/humble-ci-pre-commit.yml
- .github/workflows/jazzy-ci-pre-commit.yml
- .github/workflows/rolling-ci-pre-commit.yml
See https://github.com/ros-controls/ros2_control_ci/issues/384 for reference
> Run workflow on pushes to save cache

- control_toolbox/include/control_toolbox/rate_limiter.hpp
> Update description of limit() function in rate_limiter

- .github/workflows/rolling-pre-release.yml
> Fix branch filter

- control_toolbox/CMakeLists.txt
- control_toolbox/package.xml
> Add backward_ros

- .github/workflows/rolling-build-source.yml
> Fix source build workflow on rolling
